CREATE OR REPLACE VIEW ISP.GCAN_INV.MI_REPORT_BAD_DATA AS 
WITH

MISSING_ACCOUNT_NUMBER AS
(
	SELECT CURRENT_DATE AS REPORT_DATE, 'MISSING ACCOUNT NUMBER' AS ERROR, FIXED_DEMAND_INDICATOR, APO_PRODUCT AS MATERIAL, APO_LOCATION AS PLANT, ORDER_GUID, ACCOUNT_NUMBER, REASON_CODE, REASON_CODE_DESCRIPT, 
	QUANTITY, TRY_TO_DATE(DATE_FROM,'YYYYMMDD') AS START_DATE, TRY_TO_DATE(DATE_TO,'YYYYMMDD') AS END_DATE, NULL AS DISCO_DATE, REQUESTOR_FOR_FIXED, FIXREQ_COMMENTS_NOTE, NULL AS CUSTOMER_NAME

	FROM TERADATA.PRD_DWH_VIEW_LMT.FIXED_REQUIREMENTS_COMBINED_VIEW
	WHERE APO_LOCATION LIKE 'A%' 
	AND YEAR(START_DATE) >= YEAR(CURRENT_DATE) - 2
	AND ACCOUNT_NUMBER IS NULL 
	AND REASON_CODE IN (90003, 90005, 90012, 90013)
	AND REGEXP_COUNT(COLLATE(FIXREQ_Comments_Note,'utf8'), '_') = 3
),


INVALID_ACCOUNT_NUMBER AS
(
	SELECT CURRENT_DATE AS REPORT_DATE, 'INVALID ACCOUNT NUMBER' AS ERROR, FIXED_DEMAND_INDICATOR, APO_PRODUCT AS MATERIAL, APO_LOCATION AS PLANT, ORDER_GUID, ACCOUNT_NUMBER, REASON_CODE, REASON_CODE_DESCRIPT, 
	QUANTITY, TRY_TO_DATE(DATE_FROM,'YYYYMMDD') AS START_DATE, TRY_TO_DATE(DATE_TO,'YYYYMMDD') AS END_DATE, NULL AS DISCO_DATE, REQUESTOR_FOR_FIXED, FIXREQ_COMMENTS_NOTE, CUSTOMER.CUSTOMERNAME AS CUSTOMER_NAME

	FROM TERADATA.PRD_DWH_VIEW_LMT.FIXED_REQUIREMENTS_COMBINED_VIEW AS MI
	LEFT JOIN TERADATA.PRD_DWH_VIEW_AGI.AGI_CUSTOMER_MASTER_V AS CUSTOMER 
	    ON MI.ACCOUNT_NUMBER = CUSTOMER.CUSTOMER
	WHERE MI.APO_LOCATION LIKE 'A%' 
	AND YEAR(START_DATE) >= YEAR(CURRENT_DATE) - 2
	AND MI.ACCOUNT_NUMBER IS NOT NULL 
	AND MI.REASON_CODE IN (90003, 90005, 90012, 90013)
	AND REGEXP_COUNT(COLLATE(MI.FIXREQ_Comments_Note,'utf8'), '_') = 3
	AND CUSTOMER_NAME IS NULL
),

DISCONTINUED_EARLY AS 
(
    SELECT CURRENT_DATE AS REPORT_DATE, 'DISCONTINUED EARLY' AS ERROR, FIXED_DEMAND_INDICATOR, APO_PRODUCT AS MATERIAL, APO_LOCATION AS PLANT, ORDER_GUID, ACCOUNT_NUMBER, REASON_CODE, REASON_CODE_DESCRIPT, 
	QUANTITY, TRY_TO_DATE(DATE_FROM,'YYYYMMDD') AS START_DATE, TRY_TO_DATE(DATE_TO,'YYYYMMDD') AS END_DATE, ECC_MATERIAL.VALID_FROM AS DISCO_DATE, REQUESTOR_FOR_FIXED, FIXREQ_COMMENTS_NOTE, NULL AS CUSTOMER_NAME

    FROM TERADATA.PRD_DWH_VIEW_LMT.FIXED_REQUIREMENTS_COMBINED_VIEW AS MI
    INNER JOIN
    (
        SELECT MATERIAL, DIV0(STANDARD_PRICE, STD_PRICE_UNIT) AS STANDARD_PRICE, VALID_FROM, DCHAIN_SALES_STATUS AS SALES_STATUS,
    
        FROM TERADATA.PRD_DWH_VIEW_LMT.ECC_MATERIAL_ATTRIBUTES_VIEW 
        WHERE WEEK_OF IN (SELECT MAX(WEEK_OF) FROM TERADATA.PRD_DWH_VIEW_LMT.ECC_MATERIAL_ATTRIBUTES_VIEW)
        AND SALES_ORG = '2900'
		AND SALES_STATUS IN ('DV', 'DG')
    ) AS ECC_MATERIAL
    ON MI.APO_PRODUCT = ECC_MATERIAL.MATERIAL
    WHERE MI.APO_LOCATION LIKE 'A%' 
    AND YEAR(START_DATE) >= YEAR(CURRENT_DATE) - 2
    AND REASON_CODE IN (90003, 90005, 90012, 90013, 90014, 90019)
	AND REGEXP_COUNT(COLLATE(MI.FIXREQ_Comments_Note,'utf8'), '_') = 3
	AND ECC_MATERIAL.VALID_FROM - START_DATE <= 28
)

SELECT * FROM MISSING_ACCOUNT_NUMBER 
UNION 
SELECT * FROM INVALID_ACCOUNT_NUMBER
UNION
SELECT * FROM DISCONTINUED_EARLY;
